### ISSUE TITLE
Refresh command does not work as expected

### ISSUE THREAD

**Issue by agember** [ahorn/nopticon#7]
[bmp_peerchange.txt](https://github.com/ahorn/nopticon/files/2554851/bmp_peerchange.txt) is a BMP stream from a simulation with the [triangle topology](https://github.com/colgate-cs-research/nopticon-data/tree/master/configs/simple/triangle). It contains a print and refresh command before each link up/down event (except for the initial link up events). Using this BMP stream and the parameters `--verbosity 0 --reach-summary 1000` produces the output [nopticon_peerchange.txt](https://github.com/ahorn/nopticon/files/2554854/nopticon_peerchange.txt).

Two things about this output are unexpected:
1) The reach-summary produced by the second print command is empty. I would expect the reach-summary to be equivalent to the reach-summary printed by the first command, except all ranks should be 1, because no rules have changed since the last refresh.
2) The ranks get progressively smaller with each successive reach-summary that is printed, even though the time between refreshes is approximately the same (15 seconds). This seems to imply that the time elapsed since the start of the experiment, not the time elapsed since the last refresh, is used as the divisor for computing the rank.

Note that this was produced using a version of nopticon that includes the edits in #6.

**Comment by ericthewry** [comment]
It looks like `analysis.reach_summary_t.global_start` is only updated in `analysis_t::update_reach_summary(timestamp_t)` if you see a timestamp that is earlier than the current value for `m_reach_summary.global_start`. 

It seems like the solution to @agember 's 2nd problem is to update `m_reach_summary.global_start` in the `reach_summary_t::refresh(timestamp_t)` method. [Currently, only `m_reach_summary.global_stop` is updated on refresh](https://github.com/ahorn/nopticon/blob/master/src/analysis.cc#L156-L165). This would cause the [adjustment done in the rank function](https://github.com/ahorn/nopticon/blob/master/src/analysis.cc#L37) to result in dividing by the time since the last refresh.

**Comment by ahorn** [comment]
I have proposed a fix in commit 75a99669720de. I have double checked that the previously empty reach-summaries contain now only endpoints ranked by 1.0.

Is this okay now?

Update: I have decreased the "boost summand" in the fix so that `test_analysis` passes.

**Comment by agember** [comment]
@ahorn I have confirmed this produces the expected behavior.

**Comment by ahorn** [comment]
OK, I have merged the issue-7 branch into master.
